apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: podinfo
  namespace: apps
spec:
  interval: 5m
  chart:
    spec:
      chart: podinfo
      version: '6.3.6'
      sourceRef:
        kind: HelmRepository
        name: podinfo
        namespace: apps
      interval: 1m
  values:
    replicaCount: 2