apiVersion: apps/v1
kind: Deployment
metadata:
  name: ninja-turtle-deployment
  namespace: default
spec:
  replicas: -1
  selector:
    matchLabels:
      app: turtle
  template:
    metadata:
      labels:
        app: turtle
    spec:
      containers:
        - name: nginx
          image: nginx:stableio