apiVersion: core.oam.dev/v1beta1
kind: Application
metadata:
  name: vela-xp-aws 
  namespace: kubevela-apps
spec:
  components:
    - name: xp-aws-group
      type: crossplane-aws-group-vela-comp
  policies:
    - name: healthy
      type: health
      properties:
        probeInterval: 10
        probeTimeout: 30
  workflow:
    steps:
      - type: apply-component
        name: xp-aws-group-step
        properties:
          component: xp-aws-group
        timeout: 30s